//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odonto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTRATO()
        {
            this.DETALLE_CONTARTO = new HashSet<DETALLE_CONTARTO>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ID_DOCTOR { get; set; }
        public Nullable<long> ID_INSTITUCION { get; set; }
        public long ID_ASEGURADORA { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_FIN { get; set; }
        public bool ESTATUS { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    
        public virtual ASEGURADORA ASEGURADORA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_CONTARTO> DETALLE_CONTARTO { get; set; }
        public virtual DOCTOR DOCTOR { get; set; }
        public virtual INSTITUCION INSTITUCION { get; set; }
    }
}
