//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odonto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIRECCION()
        {
            this.DIRECCION1 = new HashSet<DIRECCION>();
        }
    
        public long ID { get; set; }
        public string NOMBRE { get; set; }
        public string TIPO { get; set; }
        public Nullable<long> ID_DIRECCION { get; set; }
        public Nullable<long> ID_PACIENTE { get; set; }
        public Nullable<long> ID_DOCTOR { get; set; }
        public Nullable<long> ID_SECRETARIA { get; set; }
        public Nullable<long> ID_GERENTE { get; set; }
        public bool ESTATUS { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIRECCION> DIRECCION1 { get; set; }
        public virtual DIRECCION DIRECCION2 { get; set; }
        public virtual DOCTOR DOCTOR { get; set; }
        public virtual GERENTE GERENTE { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual SECRETARIA SECRETARIA { get; set; }
    }
}
