//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odonto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE_ENFERMEDAD
    {
        public long ID { get; set; }
        public long ID_PACIENTE { get; set; }
        public long ID_ENFERMEDAD { get; set; }
    
        public virtual ENFERMEDAD ENFERMEDAD { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
