//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odonto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO_TIPO
    {
        public long ID { get; set; }
        public long ID_PAGO { get; set; }
        public long ID_TIPOPAGO { get; set; }
        public decimal MONTO { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public Nullable<long> ID_BANCO { get; set; }
        public string TIPOCHECK { get; set; }
    
        public virtual BANCO BANCO { get; set; }
        public virtual PAGO PAGO { get; set; }
        public virtual TIPOPAGO TIPOPAGO { get; set; }
    }
}
