//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odonto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIBO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECIBO()
        {
            this.PAGOes = new HashSet<PAGO>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ID_CITA { get; set; }
        public Nullable<long> ID_ASEGURADORA { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal MONTO { get; set; }
        public string ESTATUS { get; set; }
        public Nullable<System.DateTime> FEHA_MODIFICACION { get; set; }
    
        public virtual CITA CITA { get; set; }
        public virtual PACIENTE_ASEGURADORA PACIENTE_ASEGURADORA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAGO> PAGOes { get; set; }
    }
}
