//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odonto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELACION_TELEFONO
    {
        public long ID { get; set; }
        public Nullable<long> ID_DOCTOR { get; set; }
        public Nullable<long> ID_PACIENTE { get; set; }
        public Nullable<long> ID_SECRETARIA { get; set; }
        public Nullable<long> ID_GERENTE { get; set; }
        public long ID_TELEFONO { get; set; }
    
        public virtual DOCTOR DOCTOR { get; set; }
        public virtual GERENTE GERENTE { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual TELEFONO TELEFONO { get; set; }
        public virtual SECRETARIA SECRETARIA { get; set; }
    }
}
